export enum NetworkEnum {
  BTC="BTC",
  LTC="LTC",
  DOGE="DOGE",
  ZEC="ZEC",
  DASH="DASH",
  BTCTEST="BTCTEST",
  DOGETEST="DOGETEST",
  ZECTEST="ZECTEST",
  DASHTEST="DASHTEST",
  LTCTEST="LTCTEST",
  ERC20="ERC20",
  TRC20="TRC20"

}